### ISSUE TITLE
TP1 Terminé

### ISSUE THREAD

**Issue by GaryOma** [PolytechLyon/2019-isi3-graph-villermet-sublet#4]
Vous trouverez sur la branche *master* l'ensemble des fichiers nécessaires pour la réalisation de ce TP.

**Comment by Slashgear** [comment]
- 👍 Rapport

- Pourquoi utiliser des paramètres avec `_` ?
https://github.com/PolytechLyon/2019-isi3-graph-villermet-sublet/blob/feccbfee004ec70ea3baa6c4f316aef9e98dc7fa/src/main/java/graph/UndirectedGraph.java#L8-L17

- A quoi sert votre constructeur ici ?

**Comment by GaryOma** [comment]
> Pourquoi utiliser des paramètres avec _ ?

On a oublié de les enlever lors du développement, et ils se sont *accumulés*. [Corrigé ici](https://github.com/PolytechLyon/2019-isi3-graph-villermet-sublet/commit/d001567c46aba0571cd64e8cb0fc35f369737e16)

> A quoi sert votre constructeur ici ?

Pareil, oubli de notre part de l'avoir enlevé. [Corrigé ici](https://github.com/PolytechLyon/2019-isi3-graph-villermet-sublet/commit/19aaeb5739c435d03d883c3925ff67ac2571d19d).

Toutes ces dernières modifications sont actuellement sur *master*.
